# Generated by Django 3.2.6 on 2021-08-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='opened',
            field=models.BooleanField(default=True),
        ),
    ]
