# Generated by Django 3.2.6 on 2021-08-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_opened'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='opened',
        ),
        migrations.AddField(
            model_name='question',
            name='opened',
            field=models.BooleanField(default=True),
        ),
    ]
